### ISSUE TITLE
feat: 使用固定的签名

### ISSUE THREAD

**Issue by sti-233** [BnqDzj/BiliRoamingX-PreBuilds#4]
## 主要问题
使用 Revanced cli 打包后的apk签名随机
若无核心破解则会导致签名冲突

- 本仓库 r1999 SHA256
`3fe9213dd0ee997aa37fe3b383635cd2101eb2242724d99a368ce360a6e63bf5`
- 本仓库 play r1999 SHA256
`836f5c80c268a5b2ff3f81c8168bbf900a9ee1dad77abc6e4155905b1cd59a40`

## 功能简述
每次更新时保持签名不变

## 实现逻辑
在 Revanced cli 打包后
使用 apksigner 进行重签名

## Other
如果没必要其实也可以不修的()

**Comment by BnqDzj** [comment]
https://github.com/sti-233/Bilix-PreBuilds/blob/9cc449afff8e29254b1b8a337a02c763920b4b15/.github/workflows/Nightly-Build.yml#L112

uber-apk-signer 的 --ksAlias --ksKeyPass --ksPass 这几个参数是随便填的吗？还是有啥要求之类的？

**Comment by sti-233** [comment]
> https://github.com/sti-233/Bilix-PreBuilds/blob/9cc449afff8e29254b1b8a337a02c763920b4b15/.github/workflows/Nightly-Build.yml#L112
> 
> uber-apk-signer 的 --ksAlias --ksKeyPass --ksPass 这几个参数是随便填的吗？还是有啥要求之类的？

这个是输入签名的密码和别名、别名密码
其它应该没要求
默认v1+v2+v3
